package gates

import (
	"bytes"
	gocontext "context"
	"fmt"
	"os/exec"
	"strings"
	"time"
)

const maxOutputBytes = 1_048_576
const keepBytes = 262_144

// GateResult holds the result of a gate execution.
type GateResult struct {
	Passed   bool
	ExitCode int
	Output   string
}

// RunGate executes a gate command and returns the result.
// Exit code is authoritative: 0 = passed, non-zero = failed.
func RunGate(gateCommand string, workDir string, timeout time.Duration) (*GateResult, error) {
	if timeout <= 0 {
		timeout = 120 * time.Second
	}

	ctx, cancel := gocontext.WithTimeout(gocontext.Background(), timeout)
	defer cancel()

	// Use sh -c for commands that need PATH resolution
	cmd := exec.CommandContext(ctx, "sh", "-c", gateCommand)
	cmd.Dir = workDir

	var combined bytes.Buffer
	cmd.Stdout = &combined
	cmd.Stderr = &combined

	err := cmd.Run()

	exitCode := 0
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		} else {
			return nil, fmt.Errorf("gate command error: %w", err)
		}
	}

	output := truncateOutput(combined.String())

	return &GateResult{
		Passed:   exitCode == 0,
		ExitCode: exitCode,
		Output:   output,
	}, nil
}

func truncateOutput(output string) string {
	if len(output) <= maxOutputBytes {
		return output
	}
	dropped := len(output) - 2*keepBytes
	return output[:keepBytes] +
		fmt.Sprintf("\n[... truncated %d bytes ...]\n", dropped) +
		output[len(output)-keepBytes:]
}

// BuildContextHeader builds a pipeline context header from context entries.
func BuildContextHeader(entries []string) string {
	if len(entries) == 0 {
		return ""
	}
	var sb strings.Builder
	sb.WriteString("--- PIPELINE CONTEXT (auto-generated by Claw) ---\n")
	for i, e := range entries {
		sb.WriteString(fmt.Sprintf("[%d] %s\n", i+1, e))
	}
	sb.WriteString("---\n")
	return sb.String()
}
